This File Starts Up Rstudio Project and Deducer GUI on MSU Windows Computer
========================================================

First we set the working directory
```{r SetWorkingDirectory}
# Set working directory
setwd("C:/Users/Brad/Dropbox/CompetitionIndexer")

```
Loading the Project Template and running startup scripts
```{r ProjectTemplate}

library('ProjectTemplate')
#using load.project() will run a global.dcf config script that will load a bunch of helper functions, packages, and data sets
load.project()
```
This is how to load these packages on MSU desktop after they are installed
```{r MsuPackageLibrary}
library("apsrtable", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("brew", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("countrycode", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("devtools", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("digest", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("formatR", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("gdata", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("googleVis", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("httr", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("knitcitations", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("openair", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("quantmod", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("repmis", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("ggplot2", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("Hmisc", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("knitr", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("markdown", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("MASS", lib.loc="C:/Program Files/R/R-3.0.2/library")
library("mgcv", lib.loc="C:/Program Files/R/R-3.0.2/library")
library("rstudio", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("TH.data", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("JGR", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("Deducer", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("DeducerANOVA", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("DeducerExtras", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")
library("Zelig", lib.loc="C:/Users/Brad/Documents/R/win-library/3.0")

```
Start Console JGR with Deducer GUI, and print session info
```{r VersionSessionInfo}
JGR()
R.version
sessionInfo()

```